# Generated by Django 5.1.6 on 2026-02-14 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_index', models.FloatField(default=0.0)),
                ('loss_aversion', models.FloatField(default=0.0)),
                ('ethical_drift', models.FloatField(default=0.0)),
                ('adaptability_score', models.FloatField(default=0.0)),
                ('confidence_stability', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_profile', models.CharField(max_length=100)),
                ('analysis_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='game.gamesession')),
            ],
        ),
    ]
