# Generated by Django 6.0.2 on 2026-02-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalmetric',
            name='resource_stewardship',
            field=models.FloatField(default=0.0),
        ),
    ]
