# Generated by Django 6.0.2 on 2026-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='category',
            field=models.CharField(choices=[('Resource Crisis', 'Resource Crisis'), ('Ethical Dilemma', 'Ethical Dilemma'), ('Social Conflict', 'Social Conflict'), ('Adaptive Challenge', 'Adaptive Challenge'), ('Technological Failure', 'Technological Failure'), ('Psychological Stress', 'Psychological Stress'), ('Environmental Hazard', 'Environmental Hazard'), ('Balanced', 'Balanced')], max_length=50),
        ),
    ]
